fix: navigation bar cannot be expanded on mobile
freeCodeCamp-China/city pull request #16
Opened 2023-07-26 04:06 UTC by DunyuSong

Checklist（清单）:

- [x] Labels
- [x] Assignees
- [x] Reviewers

Closes [#10](https://github.com/freeCodeCamp-China/city/issues/10)

2023-07-26 13:18 UTC, TechQuery requested changes

2023-07-26 13:18 UTC, TechQuery commented on components/MainNavigator.tsx
> +    </Nav>
无需拘泥于原来的 HTML 结构，直接把原有外观当做原型图，用封装组件、工具类重写：
1. https://react-bootstrap.github.io/docs/components/navbar
2. https://getbootstrap.com/docs/5.3/utilities/background/

2023-07-31 15:07 UTC, TechQuery commented on components/MainNavigator.module.less
> +.nav_toggle:focus {
用嵌套语法

2023-07-31 15:09 UTC, TechQuery commented on components/MainNavigator.tsx
> +            className="link-light"
现在还有这个类吗？

2023-07-31 15:39 UTC, DunyuSong commented on components/MainNavigator.tsx
> +            className="link-light"
删掉了，用主题自带的样式

2023-07-31 15:56 UTC, TechQuery approved these changes

2023-07-31 16:07 UTC, merged