[feat] drawerNav on Conference Page; Add resolutions in package.json
freeCodeCamp-China/city pull request #17
Opened 2023-07-27 10:05 UTC by PapayaHUANG

- [x] Labels
- [ ] Assignees
- [x] Reviewers

Closes #12 

抽屉导航我就是抄隔壁开源社官网的写法。

我有两个困惑就是：
- 抽屉导航栏的状态定义在 `ConferencePage`父组件。那是单独给抽屉导航栏写一个组件，在父组件引入，还是直接就按现在这个写法，不单独写组件了？
- 使用 `getServerSideProps` 还是 `getStaticProps`? 
   我的理解是即便把 conference 的其他数据都补充完整，数据量也很少，页面除了展示基本上无交互，所以用 `getStaticProps`就可以了？

2023-07-27 11:27 UTC, TechQuery commented
> * 抽屉导航栏的状态定义在 `ConferencePage`父组件。那是单独给抽屉导航栏写一个组件，在父组件引入，还是直接就按现在这个写法，不单独写组件了？
> * 使用 `getServerSideProps` 还是 `getStaticProps`?
>   我的理解是即便把 conference 的其他数据都补充完整，数据量也很少，页面除了展示基本上无交互，所以用 `getStaticProps`就可以了？

1. 没啥复用性就不抽
2. 静态数据直接 `import`，别的啥都不用

2023-07-27 11:40 UTC, TechQuery requested changes

2023-07-27 11:40 UTC, TechQuery commented on data/conference.json
大会主页分段标题本身没啥复用性，因为每段内容结构截然不同，所以直接 hard code 即可。

2023-07-27 11:40 UTC, TechQuery commented on pages/conference.tsx
> +  }
可以独立为一个**当前页标题导航**的通用组件，参考：https://github.com/EasyWebApp/BootCell-document/blob/f40a55465deb617bb942cf442daeda54ad322db7/source/component/NavArticle.tsx#L23

2023-07-28 10:16 UTC, PapayaHUANG commented on pages/conference.tsx
> +  }
我看参考之后（oh，它仿佛就是托福阅读长难句，并且是天文题材的阅读）
理解就是写这个通用组件的时候要把 props 和 state 分开处理？

具体实现你看我提交的代码

2023-07-28 10:31 UTC, TechQuery requested changes

2023-07-28 10:31 UTC, TechQuery commented on components/DrawerNavStore.tsx
> +export default DrawerNavStore;
```suggestion
export default new DrawerNavModel();
```

2023-07-28 10:31 UTC, TechQuery commented on components/DrawerNavStore.tsx
> +        this.showDrawer = false;
```suggestion
  setShowDrawer = (show: boolean) => (this.showDrawer = show);

  closeDrawer = async () => {
    let { scrollTop } = document.scrollingElement || {};

    do {
      await sleep(0.1);

      if (scrollTop === document.scrollingElement?.scrollTop) {
        this.setShowDrawer(false);
```

2023-07-28 10:31 UTC, TechQuery commented on components/DrawerNav.tsx
> +import DrawerNavStore from './DrawerNavStore';
```suggestion
import drawerNavStore from './DrawerNavStore';
```

2023-07-28 10:31 UTC, TechQuery commented on pages/conference.tsx
> +  }
> 理解就是写这个通用组件的时候要把 props 和 state 分开处理？

不是，是查找当前页所有**标题标签**后，**自动生成目录**并可点击滚动。

通用组件我去写吧，然后你来引用。

2023-07-29 11:45 UTC, TechQuery requested changes

2023-07-29 11:45 UTC, TechQuery commented on components/DrawerNav.tsx
> +    return (
```suggestion
    const { drawerShown, closeDrawer } = this;

    return (
```
方法和属性命名有所区分

2023-07-29 11:45 UTC, TechQuery commented on components/DrawerNav.tsx
> +            <PageNav />
```suggestion
            <PageNav onItemClick={this.closeDrawer} />
```

2023-07-29 11:45 UTC, TechQuery commented on package.json
>    }
放到 `devDependencies` 下面

2023-07-29 11:45 UTC, TechQuery commented on pages/conference.tsx
> +  </>
```suggestion
    <Container as="main" className={styles.main}>
      <PageHead title="Hello Conference Page!" />

      <h1>Hello Conference Page!</h1>
      <h2>Let&apos;s get our hands dirty!</h2>

      <DrawerNav />
    </Container>
```

2023-07-30 06:03 UTC, TechQuery approved these changes

2023-07-30 06:06 UTC, merged