Issue 13 dev
freeCodeCamp-China/city pull request #18
Opened 2023-07-29 23:53 UTC by huoyueyuyuan

Checklist（清单）:

- [ ] Labels
- [ ] Assignees
- [ ] Reviewers

Closes #13

2023-07-30 08:23 UTC, TechQuery reviewed
Linux、Mac 用户在项目根目录执行一次以下命令，以确保 Git hook 执行格式化、构建脚本：
```shell
chmod +x .husky/pre-commit
chmod +x .husky/pre-push
```

2023-07-30 08:23 UTC, TechQuery commented on components/conference/Purpose.tsx
> +import styles from '../../styles/conference/Purpose.module.less';
组件样式就近放置，与组件同目录。

2023-07-30 08:23 UTC, TechQuery commented on components/conference/Purpose.tsx
> +export default Purpose;
```suggestion
export const Purpose: FC = () => (
        <div className={`${styles.abstract} pb-4 text-center`} id="section_2">
            <section className={`${styles.container} ${styles.animated}`}>
                <h2>大会宗旨</h2>
                <p>freeCodeConf 是 freeCodeCamp 中国举办的每年一度大型联动技术大会，旨在联合 freeCodeCamp 各城市本地开发者社区，促进高度垂直、高度人才集中、高度明星企业集结的互联网与软件行业技术交流。第一届 freeCodeConf 将于 2018 年 11 月 10 日在全国 12 个城市同期举办，诚邀广大开发者共享技术盛宴。</p>
            </section>
        </div>
      );
```

2023-07-30 08:23 UTC, TechQuery commented on components/conference/Review.tsx
> +                    <img src="https://conf.freecodecamp.one/assets/review1.png" className={`${styles.revImg}  `}/>
```suggestion
                <div className={styles.review_item}>
                    <img className={styles.revImg} src="https://conf.freecodecamp.one/assets/review1.png" />
```

2023-07-30 08:23 UTC, TechQuery commented on components/conference/Situation.tsx
> +                </div>
```suggestion
                <ul className="sumary">
                    <li>
                      <strong>时间：</strong>
                      <time dateTime="2018-11-10">2018 年 11 月 10 日</time>
                    </li>
                    <li>
                      <strong>地点:</strong>
                      <span>上海、天津、深圳、成都、西安、杭州、广州、武汉、郑州、济南（北京站、重庆站因特殊原因取消，望谅解）</span>
                    </li>
                    <li>
                        <strong>会议规模：</strong>
                        <span>1800+ 参会者</span>
                    </li>
                    <li>
                      <strong>参会人员：</strong>
                      <span>前端开发者、区块链开发者、CTO、架构师、相关技术从业者</span>
                    </li>
                    <li>
                      <strong>主办方：</strong>
                      <span>freeCodeCamp 中文社区</span>
                    </li>
                </ul>
```

2023-07-30 08:23 UTC, TechQuery commented on styles/conference/Purpose.module.less
> +        margin: 0; // 可以考虑用 m-0 代替
可以把注释中说的用上，再删除注释。

2023-07-30 08:23 UTC, TechQuery commented on styles/conference/Purpose.module.less
> +@-webkit-keyframes animated{
```suggestion
    animation: animated .5s ease-in-out forwards;
}

@keyframes animated {
```
现代 CSS 编译器能自动处理厂商兼容性前缀

2023-07-30 08:23 UTC, TechQuery commented on styles/conference/Situation.module.less
> +    }
```suggestion
    p {
      margin:36px 0;
      &:first-child {
        margin-top: 0;
      }
    }
```

2023-07-30 08:23 UTC, TechQuery commented on pages/conference.tsx
> +    <Snap />
无**复用性**的纯静态内容无需拆组件，直接在页面内写即可，样式也可以合并，减少重复。

2023-07-30 08:39 UTC, huoyueyuyuan commented on components/conference/Purpose.tsx
> +import styles from '../../styles/conference/Purpose.module.less';
已经就近迁移

2023-07-30 09:51 UTC, TechQuery requested changes

2023-07-30 09:51 UTC, TechQuery commented on components/conference/Snap.tsx
>                          {/*-- <h4>会议</h4> --*/}
```suggestion
```

2023-07-31 17:34 UTC, TechQuery requested changes

2023-07-31 17:34 UTC, TechQuery commented on components/conference/ConferenceBase.module.less
1. 你可以先禁用 `pre-push` 脚本，但不要禁用 `pre-commit`，否则代码不会格式化
2. 能用 [Bootstrap CSS 工具类][1]的样式都替换

[1]: https://getbootstrap.com/docs/5.3/utilities/background/

2023-07-31 17:34 UTC, TechQuery commented on components/conference/ConferenceBase.tsx
> +        </div>
内容抽出 JSON，再迭代 `<ol className="list-unstyled"><li></li></ol>`。

2023-07-31 17:34 UTC, TechQuery commented on components/conference/ConferenceBase.tsx
> +        <ul className="sumary list-unstyled" >
```suggestion
        <ul className="list-unstyled">
```

2023-08-02 08:31 UTC, TechQuery requested changes

2023-08-02 08:31 UTC, TechQuery commented on components/conference/ConferenceBase.module.less
> +  }
单一嵌套无需嵌套

2023-08-02 08:31 UTC, TechQuery commented on components/conference/ConferenceBase.module.less
> +    margin: 15px 0;
改为工具类 `d-flex my-3 mx-0`

2023-08-02 08:31 UTC, TechQuery commented on components/conference/ConferenceBase.module.less
> +    -webkit-flex-wrap: wrap;
改为工具类 `flex-wrap`

2023-08-02 08:31 UTC, TechQuery commented on components/conference/ConferenceBase.module.less
> +  }
```suggestion
  .media {
    width: 45%;
    margin-top: 20px;
    padding: 0 5px;
    & + .media {
      margin-top: 20px;
    }
    img {
      width: 100px;
    }
  }
```
`revImg` 用 `w-100` 工具类替换

2023-08-02 08:31 UTC, TechQuery commented on components/conference/ConferenceBase.tsx
> +      </div>
`<ol className="list-unstyled"><li></li></ol>`

2023-08-02 14:31 UTC, TechQuery requested changes

2023-08-02 14:31 UTC, TechQuery commented on components/conference/ConferenceBase.module.less
> +}
```suggestion
.snap .media {
  img {
    width: 80px;
  }
  @media screen and (max-width: 620px) {
    width: 45%;
    margin-top: 20px;
    padding: 0 5px;
    & + .media {
      margin-top: 20px;
    }
    img {
      width: 100px;
    }
    .revImg {
      width: 100%;
    }
  }
}
.animated {
  animation: animation 0.5s ease-in-out forwards;
}

@keyframes animated {
  0% {
    left: -50px;
    opacity: 0.7;
  }
  100% {
    left: 0;
    opacity: 1;
  }
}
```

2023-08-03 08:40 UTC, TechQuery approved these changes

2023-08-03 08:41 UTC, merged