[style] add sticky-top
freeCodeCamp-China/city pull request #19
Opened 2023-07-31 16:29 UTC by PapayaHUANG

- [x] Labels
- [ ] Assignees
- [x] Reviewers

2023-07-31 17:41 UTC, TechQuery requested changes

2023-07-31 17:41 UTC, TechQuery commented on components/MainNavigator.tsx
>    return (
省略 `{ return }`

2023-07-31 17:41 UTC, TechQuery commented on components/MainNavigator.tsx
> +      className="shadow-sm sticky-top"
```suggestion
    <Navbar
      className="shadow-sm"
      bg="success"
      data-bs-theme="dark"
      sticky="top"
      expand="lg"
      collapseOnSelect
```
1. https://react-bootstrap.github.io/docs/components/navbar#sticky-top
2. https://react-bootstrap.github.io/docs/components/navbar#responsive-behaviors

2023-08-01 03:29 UTC, PapayaHUANG commented
![image](https://github.com/freeCodeCamp-China/city/assets/70144378/ac47df1a-b7a2-46f4-bce7-14736e8e134b)
现在的导航栏菜单字的颜色是设置`data-bs-theme`导致的一系列配色的设计方案（如图），所以我就没有改了，不然就把`hover`,`active`,`disabled`这些全部重写？
@TechQuery

2023-08-01 07:43 UTC, TechQuery commented
> ![image](https://github.com/freeCodeCamp-China/city/assets/70144378/ac47df1a-b7a2-46f4-bce7-14736e8e134b)
> 现在的导航栏菜单字的颜色是设置`data-bs-theme`导致的一系列配色的设计方案（如图），所以我就没有改了，不然就把`hover`,`active`,`disabled`这些全部重写？
> @TechQuery 

也可以

2023-08-01 07:46 UTC, TechQuery requested changes

2023-08-01 07:46 UTC, TechQuery commented on styles/MainNavigator.module.less
> +.navbar {
```suggestion
.nav-box {
```
这个不是 NavBar 的根节点，而是 Nav 的，所以语义改得清晰一点。

2023-08-01 09:12 UTC, PapayaHUANG commented
> > ![image](https://user-images.githubusercontent.com/70144378/257397666-ac47df1a-b7a2-46f4-bce7-14736e8e134b.png)
> > 现在的导航栏菜单字的颜色是设置`data-bs-theme`导致的一系列配色的设计方案（如图），所以我就没有改了，不然就把`hover`,`active`,`disabled`这些全部重写？
> > @TechQuery
> 
> 也可以

好，我对比了一下，就改了原生和悬停状态的文字颜色。

2023-08-01 10:07 UTC, TechQuery approved these changes

2023-08-01 10:08 UTC, merged