feat:  ConferencePage compoments : Guest & OrganizationInfo ; optimize :ConferenceBase
freeCodeCamp-China/city pull request #21
Opened 2023-08-06 01:57 UTC by huoyueyuyuan

Checklist（清单）:

- [ ] Labels
- [ ] Assignees
- [ ] Reviewers

Closes #XXXXX

2023-08-06 14:24 UTC, TechQuery requested changes

2023-08-06 14:24 UTC, TechQuery commented on components/conference/Organization.tsx
> +    .map((sponsor, index) => paserSponsor(sponsor, index));
```suggestion
  const {
    铂金赞助商: platinumItem,
  } = groupBy(sponsers, 'level');
```
https://web-cell.dev/web-utility/functions/groupBy.html

2023-08-06 14:24 UTC, TechQuery commented on components/conference/Organization.tsx
> +              </a>
直接复制粘贴主导航栏的代码

2023-08-06 14:24 UTC, TechQuery commented on components/conference/Organization.tsx
> +        </div>
```suggestion
        <section
          className={`${styles.container} mx-auto my-0 position-relative ${styles.animated}`}
        >
          <h2 className="fs-4 pt-5 px-0 pb-3">协办方（持续更新）</h2>

          <ul className="list-unstyled partners flex_box">
            <li className="partner_item ml28">
              <a
                target="_blank"
                href="https://juejin.im/timeline"
                rel="noreferrer"
              >
                <img src="https://conf.freecodecamp.one/assets/logo/juejin.png" />
              </a>
            </li>
          </ul>
        </section>
```

2023-08-06 14:24 UTC, TechQuery commented on components/conference/Organization.tsx
> +  });
```suggestion
  const partnerItem = partners?.map(({ href, imgSrc }) => (
      <Col as="li" className={styles.partner} key={imgSrc}>
        <a
          className="mx-3"
          href={href}
          target="_blank"
          rel="noreferrer"
        >
          <img className="pb-5" src={imgSrc} />
        </a>
      </Col>
    ));
```

2023-08-06 23:51 UTC, huoyueyuyuan commented on package.json
> +  },
Module not found: Can't resolve 'fs'
> 1 | import * as fs from 'fs'; 
-----------
我理解是环境问题， 读文件找不到fs

2023-08-07 11:56 UTC, TechQuery commented on package.json
> +  },
> Module not found: Can't resolve 'fs'
> > 1 | import * as fs from 'fs'; 
> -----------
> 我理解是环境问题。 如果不加上述配置，编译异常，读文件找不到fs

Node.js API 的类型提示需要安装 `@types/node`

2023-08-08 07:46 UTC, TechQuery requested changes

2023-08-08 07:46 UTC, TechQuery commented on components/conference/Guest.module.less
> +    display: block;
```suggestion
  h4 {
```

2023-08-08 07:46 UTC, TechQuery commented on components/conference/ConferenceBase.module.less
>      font-size: 14px;
```suggestion
```
正文使用浏览器默认字号，现在都是高分屏，尽量不要低于默认。

2023-08-08 07:46 UTC, TechQuery commented on components/conference/Guest.tsx
> +    >
合并

2023-08-08 07:46 UTC, TechQuery commented on components/conference/Guest.tsx
> +              <span>{position}</span>
```suggestion
              {position}
```

2023-08-08 07:46 UTC, TechQuery commented on components/conference/Organization.tsx
> +type Partner = Record<'href' | 'imgSrc', string>;
```suggestion
type Partner = Record<'href' | 'imgSrc', string>;

type Sponsor = Partner ＆ { level: number };
```

2023-08-08 07:46 UTC, TechQuery commented on components/conference/Organization.tsx
> +  }
先写成对象字面量，再用方括号取值。

2023-08-08 07:46 UTC, TechQuery commented on components/conference/Organization.tsx
> +                className={`${styles.logo} w-25`}
```suggestion
             
              href="/"
              rel="noreferrer"
            >
              <img
                className={`${styles.logo} w-25`}
                src="./freecodecamp-logo.png"
```

2023-08-08 07:46 UTC, TechQuery commented on components/conference/Organization.tsx
> +        </div>
```suggestion
        <ul className="list-unstyled">
          <li className={styles.partner_item}>
            <a
              target="_blank"
              href="https://juejin.im/timeline"
              rel="noreferrer"
            >
              <img src="/image/logo/juejin.png" />
            </a>
          </li>
        </ul>
```

2023-08-08 07:46 UTC, TechQuery commented on components/conference/Organization.tsx
> +              {sponsors.map(({ level, href, imgSrc }: Sponsor) => (
```suggestion
        {Object.values(groupBy(sponsors, 'level')).map(
          sponsors => (
            <Row
              as="ul"
              xs={2}
              sm={5}
              className="list-unstyled justify-content-around p-1"
              key={sponsors[0].level}
            >
              {sponsors.map(({ level, href, imgSrc }) => (
```
1. 语法错误
2. 自动推导

2023-08-08 07:46 UTC, TechQuery commented on components/conference/Organization.tsx
> +          {partners?.map(({ href, imgSrc }) => (
```suggestion
          {partners.map(({ href, imgSrc }) => (
```
数据和类型一定存在，就不需要 `?`。

2023-08-08 15:47 UTC, wangrunlin requested changes

2023-08-08 15:47 UTC, wangrunlin commented on components/conference/Guest.tsx
> +          <img src={'/image/speakers/' + pic} />
```suggestion
          <img src={`/image/speakers/${pic}`} />
```

2023-08-08 15:47 UTC, wangrunlin commented on components/conference/Organization.tsx
> +                src="./freecodecamp-logo.png"
```suggestion
                src="/freecodecamp-logo.png"
```

2023-08-08 15:47 UTC, wangrunlin commented on components/conference/Guest.tsx
> +      {guests.map(({ pic, name, position }) => (
```suggestion
      {(guestData as GuestProps).map(({ pic, name, position }) => (
```

2023-08-08 15:47 UTC, wangrunlin commented on components/data/GuestData.json
只保留 `guests` 数组

2023-08-08 16:22 UTC, huoyueyuyuan commented on components/conference/Organization.tsx
> +              年，我们在将英文社区的线上课程进行本地化的基础上，尤其专注于线上线下开发者社区建设、编程教育普及以及开源文化传播，积极推动技术社区与企业、高校等的合作，促进共赢的开发者生态建设。
这个应该是 代码提交时候 自动进行的格式整理。 
实际并不会这样展示。

2023-08-08 16:28 UTC, huoyueyuyuan commented on components/conference/Guest.tsx
> +      {guests.map(({ pic, name, position }) => (
不是很理解。 这2种写法， 有本质上的区别吗 ？ 
比如影响 前端渲染， 或者 其他。

2023-08-08 16:36 UTC, TechQuery requested changes

2023-08-08 16:36 UTC, TechQuery commented on components/conference/ConferenceBase.module.less
>        }
用 `w-100` 工具类

2023-08-08 16:36 UTC, TechQuery commented on components/conference/Guest.tsx
> +          <p className="mt-3">{position}</p>
按理说名字和职位都不算一个“段落”，`<ul />` 比较合适。

2023-08-08 16:36 UTC, TechQuery commented on components/conference/Organization.tsx
> +  return (
省略 `{ return }` 让它变成**箭头函数表达式**，可以省略一级缩进。

2023-08-08 16:36 UTC, TechQuery commented on components/conference/Organization.tsx
> +                <p className="m-0">{renderLevel(level)}</p>
```suggestion
                <Badge className="m-0">{renderLevel(level)}</Badge>
```
这么短的文字，肯定也不是段落。

2023-08-09 15:25 UTC, TechQuery requested changes

2023-08-09 15:25 UTC, TechQuery commented on components/conference/ConferenceBase.tsx
>              <p className="m-0 mt-3 ">
```suggestion
          className="list-unstyled justify-content-around text-center"
        >
          <Col as="li" className={styles.media}>
            <img src="/image/meeting.png" />
             <p className="m-0 mt-3">
```

2023-08-09 15:25 UTC, TechQuery commented on components/conference/Guest.tsx
> +            <li className="fs-6 fw-bloder mt-3">{name}</li>
```suggestion
            <li className="fs-6 fw-bold mt-3">{name}</li>
```

2023-08-09 15:25 UTC, TechQuery commented on components/conference/Organization.tsx
> +              <Badge className="m-0 bg-info">{renderLevel(level)}</Badge>
```suggestion
              <Badge className="m-0" bg="info">{renderLevel(level)}</Badge>
```

2023-08-09 17:52 UTC, TechQuery requested changes

2023-08-09 17:52 UTC, TechQuery commented on components/conference/Organization.tsx
> +const { sponsors, partners } = sponsorData as OrganizationInfoProps;
```suggestion
const { sponsors, partners } = sponsorData;
```
TS 对导入的 JSON 能推导类型

2023-08-09 17:52 UTC, TechQuery commented on components/conference/Guest.tsx
> +      {(guestData as Guest[]).map(({ pic, name, position }) => (
```suggestion
export const GuestInfo: FC = () => (
  <section
    id="guests"
    className={`${styles.container} text-center mx-auto my-0 position-relative ${styles.animated}`}
  >
    <h2 className="fs-4 m-0 py-5">演讲嘉宾（持续更新）</h2>
    <Row as="ul" xs={2} sm={5} className="list-unstyled justify-content-center">
      {guestData.map(({ pic, name, position }) => (
```

2023-08-09 17:55 UTC, TechQuery commented on components/conference/Guest.tsx
> +      {guests.map(({ pic, name, position }) => (
@huoyueyuyuan @wangrunlin 看这里：https://github.com/freeCodeCamp-China/city/pull/21#discussion_r1288975355

2023-08-11 11:45 UTC, TechQuery requested changes

2023-08-11 11:45 UTC, TechQuery commented on components/conference/Guest.tsx
> +            <li className="mt-1">{position}</li>
```suggestion
          <ul className="list-unstyled mt-3">
            <li className="fs-6 fw-bolder mt-1">{name}</li>
            <li className="mt-1">{position}</li>
```
容器内元素之间和容器外的边距是两个概念

2023-08-11 11:45 UTC, TechQuery commented on components/conference/Organization.tsx
> +  <>
```suggestion
  <Container>
```
网页有个安全边距，在大屏下面看着比较舒服。

2023-08-11 12:49 UTC, TechQuery approved these changes

2023-08-11 12:54 UTC, merged