feat: ConferencePage compoments : Schedule ;
freeCodeCamp-China/city pull request #22
Opened 2023-08-06 11:05 UTC by huoyueyuyuan

Checklist（清单）:

- [ ] Labels
- [ ] Assignees
- [ ] Reviewers

Closes #15

2023-08-09 03:16 UTC, huoyueyuyuan commented
conferenceSchedule.tsx 
ConferenceSchedule.module.less
CitySchedulesData.json

2023-08-11 15:45 UTC, TechQuery requested changes

2023-08-11 15:45 UTC, TechQuery commented on components/conference/ConferenceSchedule.module.less
> +  }
`w-100` 工具类

2023-08-11 15:45 UTC, TechQuery commented on components/conference/ConferenceSchedule.module.less
> +  }
```suggestion
  a {
    display: inline-block;
    width: 10rem;
  }
```
行内元素无法设置尺寸

2023-08-11 15:45 UTC, TechQuery commented on components/conference/conferenceSchedule.tsx
> +        className={`${styles.sm_max_width} w-75 mb-2`}
```suggestion
        className={`${styles.sm_max_width} w-75 mb-2`}
        variant="pills"
```
DOM 通用属性放前面

2023-08-11 15:45 UTC, TechQuery commented on components/conference/conferenceSchedule.tsx
> +                <></>
```suggestion
              {schedules?.[0] && (
                <table className={`${styles.sm_max_width} text-start w-75`}>
                  <thead>
                    <tr>
                      <th className="p-3">时间</th>
                      <th className="p-3">主题</th>
                      <th className="p-3">演讲嘉宾</th>
                    </tr>
                  </thead>
                  <tbody>
                    {schedules.map(({ time, topic, guest }) => (
                      <tr key={topic}>
                        <td className="px-3 py-2">{time}</td>
                        <td className="py-2">{topic}</td>
                        <td className="py-2">{guest}</td>
                      </tr>
                    ))}
                  </tbody>
                </table>
```
1. https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Operators/Optional_chaining
2. 表格 `<th />`、`<td />` 数目要对上

2023-08-11 15:47 UTC, huoyueyuyuan commented on components/conference/ConferenceSchedule.module.less
> +  }
外面有个  w-75 。 
大屏 w-75 ,小屏幕  100%。

2023-08-11 16:03 UTC, huoyueyuyuan commented on components/conference/ConferenceSchedule.module.less
> +  }
className="px-3 pb-3 text-start d-inline-block" 
用工具类 d-inline-block

2023-08-11 16:18 UTC, TechQuery commented on components/conference/conferenceSchedule.tsx
> +                <></>
> 如果 演讲嘉宾信息缺失， 也要对上吗 ？ 

没有那个单元格就是空的，但如果没有单元格就很丑。

2023-08-11 16:20 UTC, TechQuery requested changes

2023-08-11 16:21 UTC, TechQuery commented on components/conference/ConferenceSchedule.module.less
> +  }
> 外面有个  w-75 。 
> 大屏 w-75 ,小屏幕  100%。 

目前没有响应式的尺寸类，这种就都写在样式文件里面。

2023-08-11 17:25 UTC, TechQuery commented on components/conference/CityScheduleInfo.module.less
> +}
```suggestion
.table_box {
  a {
    width: 10rem;
    display: inline-block;
  }
  th, td {
    &:nth-child(1) {
      width: 15%;
      @media screen and (max-width: 620px) {
        width: 20% !important;
      }
    }
    &:nth-child(2) {
      width: 20%;
      @media screen and (max-width: 620px) {
        width: 30% !important;
      }
    }
    &:nth-child(3) {
      width: 30%;
    }
  }
}
```

2023-08-11 17:26 UTC, TechQuery commented on components/conference/CityScheduleInfo.tsx
> +                className="px-3 pb-3 text-start"
```suggestion
                className="px-3 pb-3 text-start"
                target="_blank"
                href={href}
                rel="noreferrer"
```

2023-08-11 17:27 UTC, TechQuery commented on components/conference/CityScheduleInfo.tsx
> +                <table className={`${styles.sm_max_width} text-start w-100`}>
```suggestion
                <table className="text-start w-100">
```

2023-08-12 07:39 UTC, TechQuery approved these changes

2023-08-12 07:39 UTC, merged