update favicon.ico ,update NEXT_PUBLIC_SITE_NAME
freeCodeCamp-China/city pull request #30
Opened 2023-08-11 23:35 UTC by huoyueyuyuan

Checklist（清单）:

- [ ] Labels
- [ ] Assignees
- [ ] Reviewers

Closes #24

2023-08-11 23:45 UTC, huoyueyuyuan commented
旧的 favicon.ico 先做了备份 ， 确认没问题后，再删除。

2023-08-12 04:56 UTC, TechQuery requested changes

2023-08-12 04:56 UTC, TechQuery commented on .env
>  NEXT_PUBLIC_SITE_SUMMARY=React project scaffold based on TypeScript, Next.js, Bootstrap & Workbox.
把原来 HTML 中 `<meta name="description">` 内容粘过来

2023-08-12 04:57 UTC, TechQuery commented
> 旧的 favicon.ico 先做了备份 ， 确认没问题后，再删除。

脚手架的示例文件不需要备份，何况还有 Git 历史。

2023-08-12 06:49 UTC, closed without merging