feat: index compoments : CommunityCityList , City ; optimize : Carousel interval time
freeCodeCamp-China/city pull request #31
Opened 2023-08-13 17:08 UTC by huoyueyuyuan

Checklist（清单）:

- [ ] Labels
- [ ] Assignees
- [ ] Reviewers

Closes #25

2023-08-14 15:08 UTC, TechQuery requested changes

2023-08-14 15:08 UTC, TechQuery commented on pages/city/[city].tsx
> +              </Col>
```suggestion
              <Col
                as="li"
                className={`${styles.media} mt-1 pt-5 px-1 position-relative`}
                key={pic}
              >
                    <Image
                      style={{ width: '9rem', height: '9rem' }}
                      src={`/image/organizer/${pic}`}
                      alt={name}
                    />
                    <a
                      className="stretched-link text-dark fw-bolder mt-3"
                      href={link ? `/organizer/${link}` : '#'}
                    >
                      {name}
                    </a>
              </Col>
```
https://getbootstrap.com/docs/5.3/helpers/stretched-link/

2023-08-14 15:15 UTC, TechQuery requested changes
将已重构完成的 `/old/` 目录中的老数据、老图片、老代码都删掉。

2023-08-14 15:15 UTC, TechQuery commented on data/city/CommunityCityListData.json
直接使用整理过的数据：
https://github.com/freeCodeCamp-China/city/blob/ab6e661d830d172576a4a769299986f3b618d3b4/pages/api/data.ts

导入方法：
https://github.com/freeCodeCamp-China/city/blob/e3471c58c8ff132f7dde398adc58d57e3e52c985/pages/organizer/index.tsx#L6

2023-08-15 06:39 UTC, huoyueyuyuan commented on data/city/CommunityCityListData.json
old 中 ，除了guangzhou 下面 有个 history文件夹（里面有1张图片） 。 其他都已经迁移过来。
old中，index.html  有定义  history: data[city].history 。 但是没有任何关于 history的处理、展示。
这块后续怎么处理 ？

2023-08-15 09:42 UTC, TechQuery requested changes

2023-08-15 09:42 UTC, TechQuery commented on pages/organizer/[name].tsx
> +export default OrganiserPeople;
为啥改为错误拼写？

2023-08-15 09:42 UTC, TechQuery commented on pages/organizer/[name].tsx
> +import * as volunteerData from '../api/organiser';
文件名有错就改

2023-08-15 09:42 UTC, TechQuery commented on components/CommunityCityList.tsx
> +                </a>
```suggestion
                <Card.Title as="a" className="stretched-link text-dark" href={picPrefix}>
                  {name}
                </Card.Title>
```

2023-08-15 09:42 UTC, TechQuery commented on pages/[city].tsx
> +  <Col as="li" className="py-1 ">
```suggestion
  <Col as="li" className="py-1">
```

2023-08-15 09:42 UTC, TechQuery commented on pages/[city].tsx
> +                    </a>
```suggestion
                >
                  <Card.Img
                    style={{ width: '10rem', height: '10rem' }}
                    variant="top"
                    src={`/image/organizer/${pic}`}
                    alt={name}
                  />
                  <Card.Body>
                    <Card.Title
                      className="stretched-link text-dark fw-bolder mt-3"
                      href={link ? `/organizer/${link}` : '#'}
                    >
                      {name}
                    </Card.Title>
```

2023-08-15 09:42 UTC, TechQuery commented on pages/[city].tsx
> +                </ul>
```suggestion
                <div className="mt-3 fw-bolder mt-3">{name}</div>
```

2023-08-15 10:14 UTC, huoyueyuyuan commented on pages/organizer/[name].tsx
> +export default OrganiserPeople;
额， 英语差， 抄前面盾宇的写法。。。。。

2023-08-15 12:05 UTC, huoyueyuyuan commented on pages/city/[city].tsx
> +            {show && briefs?.[0] && (
.shadowIn:hover {
  opacity: 100%;
}
用  opacity 实现了。

2023-08-15 15:38 UTC, TechQuery requested changes

2023-08-15 15:38 UTC, TechQuery commented on pages/city.module.less
> +}
```suggestion
  &:hover {
    opacity: 1;
  }
}
```

2023-08-15 15:44 UTC, TechQuery requested changes

2023-08-15 15:44 UTC, TechQuery commented on pages/city/index.tsx
这个文件删掉

2023-08-15 15:44 UTC, TechQuery commented on pages/[city].tsx
用这种过于通配的路径会和同级页面冲突，请改为 `pages/city/[city].tsx`。

2023-08-16 11:22 UTC, TechQuery approved these changes

2023-08-16 11:23 UTC, merged