Optimization :  conference page and organizer page layout optimization
freeCodeCamp-China/city pull request #38
Opened 2023-08-28 03:07 UTC by huoyueyuyuan

Checklist（清单）:

- [ ] Labels
- [ ] Assignees
- [ ] Reviewers

Closes #35 #34

2023-08-28 14:18 UTC, TechQuery requested changes

2023-08-28 14:18 UTC, TechQuery commented on components/conference/CityScheduleInfo.tsx
> +            <div className={styles.table_box} key={city}>
为何手动控制 Tab？组件内置的控制逻辑不行吗？

2023-08-28 14:18 UTC, TechQuery commented on components/conference/CityScheduleInfo.tsx
>                </div>
外面的 `<div />` 没必要

2023-08-28 14:18 UTC, TechQuery commented on components/conference/CityScheduleInfo.tsx
> +                      <tr key={index}>
`key` 用数组序号没意义

2023-08-28 14:18 UTC, TechQuery commented on components/conference/CityScheduleInfo.tsx
> +                        <td className="p-2 align-top">{guest}</td>
`align-middle` 会不会更好？

2023-08-28 14:18 UTC, TechQuery commented on components/conference/Organization.tsx
> +              </Row>
```suggestion
                <Badge className="d-inline-block align-middle m-1 w-75" bg="info">
                  {renderLevel(level)}
                </Badge>
                <a className="d-inline-block align-middle" target="_blank" href={href} rel="noreferrer">
                  <Image className="object-fit-contain" src={imgSrc} />
                </a>
```

2023-08-28 14:18 UTC, TechQuery commented on pages/organizer/[name].tsx
> +    <Row as="ul" className="text-center pt-4 list-unstyled">
```suggestion
    <Row as="ul" className="list-unstyled pt-4 text-center">
```
与标签自身样式更相关的类放前面，与子元素相关的放后面。（下同）

2023-08-28 14:18 UTC, TechQuery commented on pages/organizer/[name].tsx
> +      </Row>
```suggestion
        {storyWithFCC.map(item => (
            <p key={item} className="first-line-indent fs-5 mt-1">{item}</p>
        ))}
```
纵向一列用布局框没意义，多个 `<p />` 自然排下来即可。

2023-08-28 15:41 UTC, huoyueyuyuan commented on components/conference/CityScheduleInfo.tsx
> +            <div className={styles.table_box} key={city}>
因为滚动栏的配置是写在Tabs上。如果把城市活动信息直接放在渲染tab的map里面，会造成滚动栏在最下方 。
大概10天前和阿林他们咨询了，他们的建议是： 定义一个变量，存选择城市的信息， 然后外面渲染显示城市的安排信息。

2023-08-28 16:44 UTC, TechQuery commented on components/conference/CityScheduleInfo.tsx
> +            <div className={styles.table_box} key={city}>
> 因为滚动栏的配置是写在Tabs上。如果把城市活动信息直接放在渲染tab的map里面，会造成滚动栏在最下方 。
> 大概10天前和阿林他们咨询了，他们的建议是： 定义一个变量，存选择城市的信息， 然后外面渲染显示城市的安排信息。

那就用官方的自定义布局模式：https://react-bootstrap.netlify.app/docs/components/tabs/#custom-tab-layout

2023-08-29 14:33 UTC, TechQuery requested changes
>

2023-08-29 14:33 UTC, TechQuery commented on components/conference/CityScheduleInfo.tsx
> +              <div className={styles.table_box} key={city}>
```suggestion
            <Tab.Pane key={city} eventKey={city} className={styles.table_box}>
```

2023-08-29 14:33 UTC, TechQuery commented on components/conference/CityScheduleInfo.tsx
>                  <a
```suggestion
                 <Button
```
这样样式更醒目

2023-08-30 08:22 UTC, TechQuery requested changes

2023-08-30 08:22 UTC, TechQuery commented on package.json
> +    "editorjs-html": "^3.4.3",
```suggestion
```

2023-08-30 08:22 UTC, TechQuery commented on package.json
> +    "prismjs": "^1.29.0",
```suggestion
```

2023-08-30 08:22 UTC, TechQuery commented on components/PageHead.tsx
> +      {title && ' - '}
这里干嘛改回去？

2023-08-30 08:22 UTC, TechQuery commented on packages.d.ts
> +}
```suggestion
```
整个项目都没有用到编辑器，为什么要添加呢？

2023-08-30 08:50 UTC, huoyueyuyuan commented on components/PageHead.tsx
> +      {title && ' - '}
抄的时候，忘记了

2023-08-30 08:51 UTC, huoyueyuyuan commented on packages.d.ts
> +}
直接无脑抄，没去查怎么用的。

2023-08-30 09:12 UTC, TechQuery submitted a review, later dismissed

2023-08-30 09:40 UTC, TechQuery approved these changes

2023-08-30 09:40 UTC, merged